export const STEP = "step"
export const STEP0 = "step-0"
export const STEP1 = "step-1"
export const STEP2 = "step-2"
export const STEP3 = "step-3"
export const STEP4 = "step-4"
export const STEP5 = "step-5"
export const STEP6 = "step-6"

export const ACCUEIL = "Accueil"
export const RDV = "Rendez-vous"
export const PROFIL = "Profil"
export const TRANSACTION = "Transactions"
export const PARAMETRE = "Paramètres"
export const DECONNEXION = "Déconnexion"
export const DETAIL_RDV = "detail_rdv"
